### PR TITLE
Changes for Ubuntu 15.04, see issue #16

### PR DESCRIPTION
**Pull request by fulv**

### CODE REVIEW

**Comment by fulv** [comment]
I created a `requirements.yml` to replace the `requirements.txt`, so that I could specify a git URL for the ansible.plone_server for version 4.3.5.  I did not include it here to keep a separation between the Ubuntu 15.04 stuff and the Plone 4.3.5 stuff.

**Comment by smcmahon** [comment]
How about opening a new branch in this repo for this purpose? We may be fiddling with this for a while and we've got to make sure we don't break on the most recent LTS, which is the primary target.

**Comment by fulv** [comment]
Sounds good!  Although I think I'll need some additional permissions to be able to create a new branch here.  It didn't let me push my branch the other day.
I have some additional ideas from the work I've done since yesterday.

**Comment by smcmahon** [comment]
Please try again. I'd naïvely assumed that new repos were automatically r/w for the developers team. I guess there's no magic, so I added access for both this and ansible.plone_server.

**Comment by fulv** [comment]
Thanks, I just got the subscription notification that I have push access,
so I should be set.

**Pull request closed without merging**
