### PR TITLE
Make it work on CentOS.

### PR DESCRIPTION
**Pull request by fulv**
I tested this on a CentOS 7.1 x64, and on the Trusty vagrant vm.

### CODE REVIEW

**Comment by svx** [comment]
Would you mind to update also the docs in /docs, currently there is no mention of CentOS.

And would you mind to update the Vagrantfile in https://github.com/plone/ansible-playbook/blob/fulv-centos/Vagrantfile and add there CentOS, too ?

Thanks for all the awesome work !

**Comment by smcmahon** [comment]
Testing! Thanks!

**Comment by fulv** [comment]
@svx Done.

**Comment by svx** [comment]
@fulv Great ! Awesome ! Thanks !

**Comment by smcmahon** [comment]
I'm closing this particular pull request because I'm doing some additional fiddling with fulv-centos to get the tests working. Looking good so far ...

**Comment by smcmahon** [comment]
Merged!

Problems remaining:

fail2ban

firewall

varnish lacking gzip

**Comment by svx** [comment]
@smcmahon fail2ban is available via EPEL [https://fedoraproject.org/wiki/EPEL]

**Comment by fulv** [comment]
Awesome, thanks!

**Pull request closed without merging**
