### PR TITLE
sensible defaults for Python 3

### PR DESCRIPTION
**Pull request by tkimnguyen**

### CODE REVIEW

**Comment by stevepiercy** [comment]
See also #138 and #139.

**Comment by stevepiercy** [comment]
We should also update: https://github.com/plone/ansible.plone_server/blob/master/defaults/main.yml#L9

**Comment by stevepiercy** [comment]
And this:
https://github.com/plone/ansible.plone_server/blob/master/defaults/main.yml#L99

**Comment by smcmahon** [comment]
Be cautious about updating the defaults/main.yml files. That runs a serious risk of breaking existing installations and causing considerable harm. If you really have to do it, make sure that the documentation screams the risk of pulling the updated version.

On the other hand, updating the sample files is a great way of communicating good practices without breaking existing installs.

**Pull request merged**
